created tests for n, nn, sw, and like
RocketPartners/rocket-inversion pull request #96
Opened 2019-05-03 16:07 UTC by rmbasilio

Tests for n, nn, sw, and like

2019-05-09 22:18 UTC, wellsb1 requested changes
Every one of theses test cases needs to check the actual data not just the results length.

Please see comments on @hayas PR #97 for consistency.

Also, if these operators are not tested in TestSqlQuery, please add tests for them there too.

2019-05-09 22:18 UTC, wellsb1 commented on src/test/java/io/rocketpartners/cloud/action/rest/TestRestGetActions.java
> +      assertEquals(5, json.getArray("data").length());
This needs to actually check that the shipregion field is null.

See comments on https://github.com/RocketPartners/rocket-inversion/pull/97 for consistency.

2019-05-09 22:18 UTC, wellsb1 commented on src/test/java/io/rocketpartners/cloud/action/rest/TestRestGetActions.java
> +      assertEquals(0, json.getArray("data").length());
same, need to check the data in addition to results size.

2019-05-10 02:54 UTC, rmbasilio commented
> Every one of theses test cases needs to check the actual data not just the results length.
> 
> Please see comments on @hayas PR #97 for consistency.
> 
> Also, if these operators are not tested in TestSqlQuery, please add tests for them there too.

Changes made to match updated requirements. I believe I saw these operators in TestSqlQuery, though it's a little bit hard to tell for sure with all the tests cases jammed into a single test.

2019-05-10 18:26 UTC, wellsb1 approved these changes

2019-05-10 18:26 UTC, merged