Test cases for "ew", "lt", "le", "in", "out", "w"
RocketPartners/rocket-inversion pull request #97
Opened 2019-05-06 08:53 UTC by hayas

2019-05-07 14:39 UTC, kfrankic commented on src/test/java/io/rocketpartners/cloud/action/rest/TestRestGetActions.java
> +      ArrayNode data = res.getJson().getArray("data");
Use res.data() here, instead of res.getJson().getArray("data");

2019-05-07 15:01 UTC, kfrankic requested changes
Make changes!

2019-05-08 14:24 UTC, kfrankic commented on src/test/java/io/rocketpartners/cloud/action/rest/TestRestGetActions.java
> +      json = res.getJson();
'json' is no longer used in this test.

2019-05-09 22:05 UTC, wellsb1 requested changes
Additinally, please add tests for these to TestSqlQuery as you did for emp and nemp.

2019-05-09 22:05 UTC, wellsb1 commented on src/test/java/io/rocketpartners/cloud/action/rest/TestRestGetActions.java
> +      boolean assertion = true;
Functionally good.  Would prefer this...

assertTrue(data.size() > 0);
for (Object o : data)
{
  assertTrue(((ObjectNode)o).getString("shipname").endsWith("Chevalier")));
}

2019-05-09 22:05 UTC, wellsb1 commented on src/test/java/io/rocketpartners/cloud/action/rest/TestRestGetActions.java
> +      assertEquals(7, res.data().length());
Please check the employeeid of the returned values to make sure the do not include 1 or 2.  Can leave the 7 length check but one of those seven could be 1 or 2.

2019-05-09 22:05 UTC, wellsb1 commented on src/test/java/io/rocketpartners/cloud/action/rest/TestRestGetActions.java
> +      assertEquals(4, res.data().length());
Please also check that the response values include "ondon".

2019-05-10 09:04 UTC, hayas commented
Resolved all the comments and added tests for these operators in TestSqlQuery

2019-05-13 12:27 UTC, wellsb1 approved these changes

2019-05-13 12:27 UTC, wellsb1 commented
@hayas please resolve this merge conflict and merge.

2019-05-13 13:01 UTC, hayas commented
Resolved the merge conflicts

2019-05-15 11:32 UTC, wellsb1 approved these changes

2019-05-15 11:34 UTC, wellsb1 commented
@kfrankic I think you requested changes here.  Can you please review?

@hayas, please go ahead and merge after you get Kevin's approval.

CC @jwwiggs

2019-05-15 14:57 UTC, kfrankic approved these changes

2019-05-16 09:22 UTC, merged