Inversion support for emp, nemp for sql; testcase emp, nemp
RocketPartners/rocket-inversion pull request #98
Opened 2019-05-06 11:17 UTC by hayas

2019-05-07 14:57 UTC, kfrankic commented on src/test/java/io/rocketpartners/cloud/action/rest/TestRestGetActions.java
> +      List<Map<String, Object>> resultsList = res.data().asList();
List<ObjectNode> list = res.data().asList() makes more sense here.

2019-05-07 15:00 UTC, kfrankic requested changes
Make changes

2019-05-08 14:02 UTC, kfrankic commented on src/test/java/io/rocketpartners/cloud/action/rest/TestRestGetActions.java
> +      for (Map<String, Object> result : list)
You updated 'list' but failed to update Map<String, Object> to ObjectNode

2019-05-09 21:53 UTC, wellsb1 commented on src/test/java/io/rocketpartners/cloud/action/rest/TestRestGetActions.java
> +         if (result.get("shipregion") != null && result.get("shipregion") != "")
result.get("shipregion") != "" is NEVER valid Java.  You have to use .equals().  != checks object equality, not value equality.  

I would write this this way:

for(ObjectNode result : list)
{
  String shipregion = result.getString("shipregion");
  if(!Utils.empty(shipregion))
    fail("shipregion was supposed to be empty but was: '" + shipregion + "'");
}

There is no reason to continue the loop if any one of the values is not empty.

2019-05-09 21:54 UTC, wellsb1 commented on src/test/java/io/rocketpartners/cloud/action/rest/TestRestGetActions.java
> +   public void testNemp01() throws Exception
See comments for testEmp01() above.  Same thing here.

2019-05-09 21:55 UTC, wellsb1 commented on src/test/java/io/rocketpartners/cloud/action/sql/TestSqlQuery.java
> +      tests.add(new RqlTest("emp(startYear)", //
Nice job knowing to add these tests cases.  I did not explicitly ask for them.  This was the right thing to do.

2019-05-09 21:56 UTC, wellsb1 requested changes
See inline comments.

2019-05-10 09:31 UTC, hayas commented
Resolved all the requested changes

2019-05-13 12:22 UTC, wellsb1 approved these changes

2019-05-13 12:22 UTC, merged