Returned auto generated key collection
RocketPartners/rocket-inversion pull request #99
Opened 2019-05-07 14:16 UTC by hayas

2019-05-07 14:50 UTC, wellsb1 requested changes
We want the first column of each row of the generated keys result set, not all of the columns of the first row.  This is a clear misunderstanding of what we are trying to accomplish.  The DB is generating primary keys for rows that are inserted by the upsert statement.  Please do some more research on this JDBC capability to make sure you understand the requirement.  Please write a test case as well.  Any attempt to run this code should make it very obvious that this is structurally incorrect.

2019-05-08 14:52 UTC, hayas commented
1. If a row was inserted or updated, Statement.getGeneratedKeys() will have the key for that row. If the row was not modified (insert ignore or insert ... on duplicate key update that results in a no-op, executeBatch() returns, there is no key.
2. The ResultSet returned by getGeneratedKeys will have the entries for successfully inserted rows.

2019-05-08 20:58 UTC, wellsb1 commented on src/test/java/io/rocketpartners/cloud/action/sql/TestSqlPostAction.java
> +            assertEquals(toUpsert.size() - 1, generatedKeys.size());
You should be testing the value of the returned keys.  My original template included guidance.

2019-05-09 21:16 UTC, wellsb1 approved these changes

2019-05-09 21:16 UTC, merged